apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node    # Ensure this matches the label in the template
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: test89678.azurecr.io/node_app:v1 
        ports:
        - containerPort: 80
