apiVersion: v1
kind: Service
metadata:
  labels:
    app: aj-deployment
  name: aj-service
  namespace: aj
spec:
  ports:
  - nodePort: 30132
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aj-deployment
  type: LoadBalancer

